cc_library(
  name = "mindmath",
  srcs = ["src/generator.cpp"],
  hdrs = ["include/mindmath/example_view.h",
          "include/mindmath/generator.h",
          "include/mindmath/operation.h",
          "include/mindmath/setup.h"],
  strip_include_prefix = "include",
  visibility = ["//visibility:public"]
)