cc_library(
  name = "mindmath.mindmath",
  srcs = ["src/generator.cpp"],
  hdrs = glob(["include/mindmath/*.h"]),
  strip_include_prefix = "include",
  visibility = ["//visibility:public"],
  deps = ["//common:mindmath.common"]
)